# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BailaimaPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setMinimumSize(QtCore.QSize(200, 200))
        self.start_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.start_btn.setFont(font)
        self.start_btn.setStyleSheet("/*按钮普通态*/\n"
"QPushButton {\n"
"    color: #000000;\n"
"    /*背景颜色*/\n"
"    background-color: #ffffff;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #dddddd;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid #7084D4;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.setting_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_btn.sizePolicy().hasHeightForWidth())
        self.setting_btn.setSizePolicy(sizePolicy)
        self.setting_btn.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        self.setting_btn.setFont(font)
        self.setting_btn.setStyleSheet("/*按钮普通态*/\n"
"QPushButton {\n"
"    color: #000000;\n"
"    /*背景颜色*/\n"
"    background-color: #ffffff;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #dddddd;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid #7084D4;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}")
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout.addWidget(self.setting_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_btn.sizePolicy().hasHeightForWidth())
        self.exit_btn.setSizePolicy(sizePolicy)
        self.exit_btn.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(36)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("/*按钮普通态*/\n"
"QPushButton {\n"
"    color: #000000;\n"
"    /*背景颜色*/\n"
"    background-color: #ffffff;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #dddddd;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid #7084D4;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}")
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout.addWidget(self.exit_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.loglist_table = QtWidgets.QTableWidget(self.centralwidget)
        self.loglist_table.setObjectName("loglist_table")
        self.loglist_table.setColumnCount(0)
        self.loglist_table.setRowCount(0)
        self.verticalLayout.addWidget(self.loglist_table)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.init_num_text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.init_num_text.setFont(font)
        self.init_num_text.setObjectName("init_num_text")
        self.horizontalLayout_2.addWidget(self.init_num_text)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.current_num_text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.current_num_text.setFont(font)
        self.current_num_text.setObjectName("current_num_text")
        self.horizontalLayout_3.addWidget(self.current_num_text)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.stop_num_text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.stop_num_text.setFont(font)
        self.stop_num_text.setObjectName("stop_num_text")
        self.horizontalLayout_4.addWidget(self.stop_num_text)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.status_num_text = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.status_num_text.setFont(font)
        self.status_num_text.setObjectName("status_num_text")
        self.horizontalLayout_5.addWidget(self.status_num_text)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_btn.setText(_translate("MainWindow", "开始"))
        self.setting_btn.setText(_translate("MainWindow", "设置"))
        self.exit_btn.setText(_translate("MainWindow", "退出"))
        self.label_2.setText(_translate("MainWindow", "初始值："))
        self.init_num_text.setText(_translate("MainWindow", "123123"))
        self.label_3.setText(_translate("MainWindow", "当前值："))
        self.current_num_text.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "终止值:"))
        self.stop_num_text.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "当前状态："))
        self.status_num_text.setText(_translate("MainWindow", "TextLabel"))
