# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BailaimaRegisterPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 253)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.register_input = QtWidgets.QTextBrowser(Dialog)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.register_input.setFont(font)
        self.register_input.setObjectName("register_input")
        self.horizontalLayout.addWidget(self.register_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.activation_input = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activation_input.sizePolicy().hasHeightForWidth())
        self.activation_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.activation_input.setFont(font)
        self.activation_input.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.activation_input.setObjectName("activation_input")
        self.horizontalLayout_2.addWidget(self.activation_input)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("/*按钮普通态*/\n"
"QPushButton {\n"
"    color: #000000;\n"
"    /*背景颜色*/\n"
"    background-color: #ffffff;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #dddddd;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid #7084D4;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "注册信息"))
        self.register_input.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\',\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "激活码"))
        self.save_btn.setText(_translate("Dialog", "注册"))
