# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BailaimaSettingPageUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 650)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.print_ip_input = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.print_ip_input.sizePolicy().hasHeightForWidth())
        self.print_ip_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.print_ip_input.setFont(font)
        self.print_ip_input.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.print_ip_input.setObjectName("print_ip_input")
        self.horizontalLayout.addWidget(self.print_ip_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.error_correction_select = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.error_correction_select.sizePolicy().hasHeightForWidth())
        self.error_correction_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.error_correction_select.setFont(font)
        self.error_correction_select.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.error_correction_select.setObjectName("error_correction_select")
        self.error_correction_select.addItem("")
        self.error_correction_select.addItem("")
        self.error_correction_select.addItem("")
        self.error_correction_select.addItem("")
        self.horizontalLayout_7.addWidget(self.error_correction_select)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.fixed_input1 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixed_input1.sizePolicy().hasHeightForWidth())
        self.fixed_input1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.fixed_input1.setFont(font)
        self.fixed_input1.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.fixed_input1.setObjectName("fixed_input1")
        self.horizontalLayout_3.addWidget(self.fixed_input1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(120, 0))
        self.label_5.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.fixed_input2 = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fixed_input2.sizePolicy().hasHeightForWidth())
        self.fixed_input2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.fixed_input2.setFont(font)
        self.fixed_input2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.fixed_input2.setObjectName("fixed_input2")
        self.horizontalLayout_4.addWidget(self.fixed_input2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.basen_select = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.basen_select.sizePolicy().hasHeightForWidth())
        self.basen_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.basen_select.setFont(font)
        self.basen_select.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}\n"
"")
        self.basen_select.setObjectName("basen_select")
        self.basen_select.addItem("")
        self.basen_select.addItem("")
        self.basen_select.addItem("")
        self.basen_select.addItem("")
        self.horizontalLayout_12.addWidget(self.basen_select)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.start_num_input = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_num_input.sizePolicy().hasHeightForWidth())
        self.start_num_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.start_num_input.setFont(font)
        self.start_num_input.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.start_num_input.setObjectName("start_num_input")
        self.horizontalLayout_2.addWidget(self.start_num_input)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(120, 0))
        self.label_7.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.end_num_input = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_num_input.sizePolicy().hasHeightForWidth())
        self.end_num_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.end_num_input.setFont(font)
        self.end_num_input.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.end_num_input.setObjectName("end_num_input")
        self.horizontalLayout_6.addWidget(self.end_num_input)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(120, 0))
        self.label_6.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.step_num_input = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_num_input.sizePolicy().hasHeightForWidth())
        self.step_num_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.step_num_input.setFont(font)
        self.step_num_input.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.step_num_input.setObjectName("step_num_input")
        self.horizontalLayout_5.addWidget(self.step_num_input)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.direction_select = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direction_select.sizePolicy().hasHeightForWidth())
        self.direction_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.direction_select.setFont(font)
        self.direction_select.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.direction_select.setObjectName("direction_select")
        self.direction_select.addItem("")
        self.direction_select.addItem("")
        self.horizontalLayout_8.addWidget(self.direction_select)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.repeat_num_input = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeat_num_input.sizePolicy().hasHeightForWidth())
        self.repeat_num_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.repeat_num_input.setFont(font)
        self.repeat_num_input.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.repeat_num_input.setObjectName("repeat_num_input")
        self.horizontalLayout_9.addWidget(self.repeat_num_input)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setMinimumSize(QtCore.QSize(120, 0))
        self.label_11.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.guide_num_input = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guide_num_input.sizePolicy().hasHeightForWidth())
        self.guide_num_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.guide_num_input.setFont(font)
        self.guide_num_input.setStyleSheet("QLineEdit {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}")
        self.guide_num_input.setObjectName("guide_num_input")
        self.horizontalLayout_10.addWidget(self.guide_num_input)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setMinimumSize(QtCore.QSize(120, 0))
        self.label_12.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.repeat_num_select = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeat_num_select.sizePolicy().hasHeightForWidth())
        self.repeat_num_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.repeat_num_select.setFont(font)
        self.repeat_num_select.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}\n"
"")
        self.repeat_num_select.setObjectName("repeat_num_select")
        self.repeat_num_select.addItem("")
        self.repeat_num_select.addItem("")
        self.horizontalLayout_11.addWidget(self.repeat_num_select)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.product_num_select = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_num_select.sizePolicy().hasHeightForWidth())
        self.product_num_select.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.product_num_select.setFont(font)
        self.product_num_select.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 2px 1px 2px;\n"
"    min-width: 9em;\n"
"    min-height:2em;\n"
"}\n"
"")
        self.product_num_select.setObjectName("product_num_select")
        self.product_num_select.addItem("")
        self.product_num_select.addItem("")
        self.horizontalLayout_13.addWidget(self.product_num_select)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.save_btn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setKerning(True)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("/*按钮普通态*/\n"
"QPushButton {\n"
"    color: #000000;\n"
"    /*背景颜色*/\n"
"    background-color: #ffffff;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #dddddd;\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid #7084D4;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-top: 3px;\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout.addWidget(self.save_btn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "软件设置"))
        self.label_2.setText(_translate("Dialog", "喷码机IP地址"))
        self.print_ip_input.setPlaceholderText(_translate("Dialog", "请输入喷码机的IP地址"))
        self.label_8.setText(_translate("Dialog", "纠错等级"))
        self.error_correction_select.setItemText(0, _translate("Dialog", "M级"))
        self.error_correction_select.setItemText(1, _translate("Dialog", "L级"))
        self.error_correction_select.setItemText(2, _translate("Dialog", "H级"))
        self.error_correction_select.setItemText(3, _translate("Dialog", "Q级"))
        self.label_4.setText(_translate("Dialog", "内容1"))
        self.fixed_input1.setPlaceholderText(_translate("Dialog", "请输入文本"))
        self.label_5.setText(_translate("Dialog", "内容2"))
        self.fixed_input2.setPlaceholderText(_translate("Dialog", "请输入文本"))
        self.label_14.setText(_translate("Dialog", "生产进制"))
        self.basen_select.setItemText(0, _translate("Dialog", "10"))
        self.basen_select.setItemText(1, _translate("Dialog", "16"))
        self.basen_select.setItemText(2, _translate("Dialog", "26"))
        self.basen_select.setItemText(3, _translate("Dialog", "32"))
        self.label_3.setText(_translate("Dialog", "起始值"))
        self.start_num_input.setPlaceholderText(_translate("Dialog", "请输入起始值"))
        self.label_7.setText(_translate("Dialog", "终止值"))
        self.end_num_input.setPlaceholderText(_translate("Dialog", "请输入终止值"))
        self.label_6.setText(_translate("Dialog", "步进"))
        self.step_num_input.setPlaceholderText(_translate("Dialog", "请输入步进大小"))
        self.label_9.setText(_translate("Dialog", "方向"))
        self.direction_select.setItemText(0, _translate("Dialog", "递增"))
        self.direction_select.setItemText(1, _translate("Dialog", "递减"))
        self.label_10.setText(_translate("Dialog", "重复计数次数"))
        self.repeat_num_input.setPlaceholderText(_translate("Dialog", "请输入重复次数"))
        self.label_11.setText(_translate("Dialog", "引导字符"))
        self.guide_num_input.setPlaceholderText(_translate("Dialog", "请输入引导字符"))
        self.label_12.setText(_translate("Dialog", "循环"))
        self.repeat_num_select.setItemText(0, _translate("Dialog", "是"))
        self.repeat_num_select.setItemText(1, _translate("Dialog", "否"))
        self.label_13.setText(_translate("Dialog", "生成流水号"))
        self.product_num_select.setItemText(0, _translate("Dialog", "是"))
        self.product_num_select.setItemText(1, _translate("Dialog", "否"))
        self.save_btn.setText(_translate("Dialog", "保存设置"))
